// File generated by FlutterFire CLI.
//
// ⚠️ THIS IS A PLACEHOLDER, NOT A REAL CONFIG FILE. ⚠️
//
// Do NOT edit this by hand and do NOT try to run the app with the values
// below — they are fake and will not connect to any real project.
//
// Instead, from your project root, run:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// and select your Firebase project + the platforms you're targeting.
// That command will OVERWRITE this exact file with real values pulled
// from your Firebase project automatically. See the README for the full
// walkthrough.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform — run `flutterfire configure` to generate real options for it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtGIA0jjFEnaadAGHtzLQHbN6JvXSL6z4',
    appId: '1:498249162091:web:f6f0a7112c429dc211802e',
    messagingSenderId: '498249162091',
    projectId: 'cozyaquapet',
    authDomain: 'cozyaquapet.firebaseapp.com',
    storageBucket: 'cozyaquapet.firebasestorage.app',
    measurementId: 'G-DH59E93TXJ',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'REPLACE_ME',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = web;
}
